### ISSUE TITLE
Getting connection failed with pkce = true

### ISSUE THREAD

**Issue by originalkamaal** [SijuKJ/desktopoauth2.0#7]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection failed
#0      IOClient.send (package:http/src/io_client.dart:94:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:166:12)
<asynchronous suspension>
#3      DesktopOAuth2._fetchAccessToken (package:desktopoauth2/src/desktop_oauth2.dart:68:22)
<asynchronous suspension>
#4      OAuthService.authorize (package:open_project_client/core/helpers/oauth.dart:49:9)
<asynchronous suspension>

**Comment by kinga112** [comment]
Any more details about the error you are facing? Which oauth service?
